### ISSUE TITLE
Hide video controls

### ISSUE THREAD

**Issue by ajbraus** [erost/ng-videosharing-embed#26]
Hi, I love the module.

Is there a way to add the option "hide-controls='true'" so the controls of each video player are hidden?

Thanks!

**Comment by erost** [comment]
Hi ajbraus,
that only works in youtube by adding controls=0 (see the documentation here: https://developers.google.com/youtube/player_parameters#controls )

Vimeo doesn't support that option currently, I should probably look into updating the dailymotion profile.

**Comment by erost** [comment]
It should work on Dailymotion by using chromeless. 
If you test it, let me know the outcome.
