### ISSUE TITLE
Enable Youtube JS API

### ISSUE THREAD

**Issue by wesley3523** [erost/ng-videosharing-embed#27]
Is it possible to build in a mute and setVolume? I'd like to start some videos muted or to a specified volume.

Thanks

**Comment by erost** [comment]
I added the necessary support for the Youtube JS API. Simirarly to vimeo, you should add an iframeId parameter, and then follow the youtube documentation for the necessary parameters.

**Comment by wesley3523** [comment]
Do you have a example for me? I was expecting to give some attibute something like for example set-volume="30" or mute="1". but i aint seeing this on the whitelist.

I would appreciate it.

**Comment by erost** [comment]
I added an example page with a rough api integration. You can start from there, and decide how it's better integrated in your site/app.

http://erost.net/ng-videosharing-embed/
