### ISSUE TITLE
width="100%" 

### ISSUE THREAD

**Issue by fabiusss** [erost/ng-videosharing-embed#30]
Congratulations to this Directive, really very helpful.
The only fault I found is when you resize the page.
I compared with iframe youtube and you do not have the same behavior responsive.

```
<iframe width="100%" height="315" src="https://www.youtube.com/embed/pjH8xFDxl-I" frameborder="0" allowfullscreen></iframe>

<embed-video id="embed-video"  width="100%" height="315"   href="http://youtu.be/pjH8xFDxl-I"></embed-video>
```

**Comment by erost** [comment]
Hi Fabiusss,
can you be more specific? I tried to reproduce the issues but I honestly don't see any difference.
Can you setup a jsFiddle/plunkr?

**Comment by fabiusss** [comment]
Hi,
I tried to use jsFiddle https://jsfiddle.net/6efqx309/5/ but it does not work, so i posted a gif animation of issue.

![output_qdjtrh](https://cloud.githubusercontent.com/assets/5826854/6503317/f8236dc4-c32b-11e4-8e4b-0c5b220ed948.gif)

**Comment by erost** [comment]
are you using any sort of responsive CSS library like bootstrap? 
That's probably where the problem is. 
It's hard to guess what could be wrong, maybe the custom tag is not properly handled during the resize? Maybe adding a class to the embed-video element will solve your issue.
