### ISSUE TITLE
Vimeo link parsing (from channel)

### ISSUE THREAD

**Issue by Maqsim** [erost/ng-videosharing-embed#33]
Hi. I use your directive in production. But I've found the directive doesn't parse links kind of `https://vimeo.com/channels/staffpicks/119904435`. `channels/*/` is a just marketing sugar.

If you want I'll create a PR for it.

Thanks.

**Comment by erost** [comment]
Can you test it out with version 0.3.2?
Thanks

**Comment by Maqsim** [comment]
@erost Yes, it's working perfectly. Thank you
