### ISSUE TITLE
Trying to enhance this module

### ISSUE THREAD

**Issue by fidoboy** [erost/ng-videosharing-embed#8]
I'm trying to add a new directive into this module to allow get the video thumbnail, so i've added thumbURL into the players configurations. This thumbURL should be a function to retrieve the thumbnail URL and here is my problem, cause it returns undefined.

here is my code (for vimeo player):

``` javascript
thumbURL: function (id) {
    var deferred = $q.defer();
    $http.jsonp('http://vimeo.com/api/v2/video/' + id + '.json?callback=JSON_CALLBACK').success(function(data) {
        var thumbs = [];
        thumbs.push(data[0]['thumbnail_small']);
        thumbs.push(data[0]['thumbnail_medium']);
        thumbs.push(data[0]['thumbnail_large']);
        deferred.resolve(thumbs);
    }).error(function() {
        deferred.reject();
    });

    return deferred.promise;
},
```

but when i call:

var VideoThumb = config.thumbURL(videoID);

it throws an error and says that thumbURL is undefined. I'm sure that my code it's wrong so any help could be appreciated ;)

**Comment by dsmithco** [comment]
So if this in the plugin now.
